version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./html:/var/www/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: search
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    ports:
      - "4306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
