apiVersion: v1
kind: Namespace
metadata:
  name: microservices

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-deployment
  namespace: microservices
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservices
  template:
    metadata:
      labels:
        app: microservices
    spec:
      containers:
        - name: microservices
          image: your-registry/microservices:latest
          ports:
            - containerPort: 80
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq

---
apiVersion: v1
kind: Service
metadata:
  name: microservices-service
  namespace: microservices
spec:
  selector:
    app: microservices
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
  namespace: microservices
data:
